---
  - name: install mysql-server
    apt: name=mysql-server
    notify:
      - mysql_secure_installation

  - name: write conf.d/mysqld.cnf
    template: >
      src=mysqld.cnf.j2
      dest=/etc/mysql/conf.d/mysqld.cnf
    notify:
      - restart mysql

  - name: write conf.d/client.cnf
    template: >
      src=client.cnf.j2
      dest=/etc/mysql/conf.d/client.cnf
    notify:
      - restart mysql