---
  - name: mysql_secure_installation
    template: >
      src=mysql_secure_installation.j2
      dest=/tmp/mysql_secure_installation
      owner=root
      group=root
      mode=0600
    when: mysql_root_password != ""
    notify:
      - launch mysql_secure_installation
      - delete mysql_secure_installation

  - name: launch mysql_secure_installation
    when: mysql_root_password != ""
    shell: cat /tmp/mysql_secure_installation | mysql_secure_installation

  - name: delete mysql_secure_installation
    when: mysql_root_password != ""
    file: >
      dest=/tmp/mysql_secure_installation
      state=absent

  - name: restart mysql
    service: >
      name=mysql
      state=restarted
      enabled=yes