# ---
# - name: Add GPG Key hellobits.com for ruby install
#   apt_key: url={{ ruby_url }}
#   tags: ruby

# - name: Add repository for ruby install
#   apt_repository: >
#     repo='{{ruby_repo_install}}'
#     state=present
#   tags: ruby

# - name: Install Ruby
#   apt: >
#     pkg={{ ruby_version }}
#     update_cache=yes
#     cache_valid_time=3600
#     state=latest
#     force=yes
#   tags: ruby

---
# Ruby from source playbook

- name: upgrade
  apt: upgrade=yes
  tags: ruby

# Install correct version of ruby from source
- name: ruby-from-src | ensure directory temporary ruby download directory is present
  file: >
    state=directory
    path={{ rubyTmpDir }}
  tags: ruby

- name: ruby-from-src | Download ruby source
  get_url: >
    url={{rubyUrl}}
    dest={{rubyTmpDir}}
  tags: ruby

- name: ruby-from-src | ensure ruby is extracted
  command: >
    tar -xf {{rubyCompressedFile}}
    chdir={{rubyTmpDir}}
    creates={{tmpRubyPath}}
  tags: ruby

- name: ruby-from-src | ensure ruby is configured
  command: >
    ./configure
    chdir={{tmpRubyPath}}
    creates={{tmpRubyPath}}/Makefile
  tags: ruby

- name: ruby-from-src | ensure ruby is compiled
  command: >
    make
    chdir={{tmpRubyPath}}
    creates={{tmpRubyPath}}/ruby
  tags: ruby

- name: ruby-from-src | ensure ruby is installed
  command: >
    make install
    chdir={{tmpRubyPath}}
    creates=/usr/local/bin/ruby
  tags: ruby

- name: Gem install bundler
  gem: >
    name=bundler
    user_install=no
    state=latest
  tags: ruby